version: 0.2
phases:
  install:
    commands:
      - npm i -g typescript
      - npm i
  build:
    commands:
      - npm run build
      - rm -rf src
artifacts:
    type: zip
    files:
      - '**/*'
